name: CI Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up environment variable for branch
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          working-directory: ${{ env.BRANCH }}

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: go test -race -count=100 ./...

  build:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: go build -v -o ./bin/gomigrator ./cmd/gomigrator

  deploy:
    name: Deploy to Develop Environment
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Copy Binary to Deployment Server
        run: scp -o StrictHostKeyChecking=no ./bin/gomigrator user@develop-server:/path/to/deployment

      - name: Restart Service
        run: ssh user@develop-server 'sudo systemctl restart gomigrator'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
